
import { Permit, PermitStatus } from "@/lib/types";

export const mockPermits: Permit[] = [
    {
        id: "1",
        trackingId: "TRK-2024001",
        type: "informasi-publik",
        applicantName: "Budi Santoso",
        applicantEmail: "budi@example.com",
        applicantPhone: "081234567890",
        agencyName: "Universitas Brawijaya",
        agencyCategory: "Institusi Pendidikan",
        subject: "Permohonan Data Hidrologis Tahun 2023",
        description: "Kami membutuhkan data curah hujan dan debit air sungai untuk keperluan penelitian akademis mahasiswa tingkat akhir.",
        submissionDate: new Date("2024-02-01").toISOString(),
        status: "diajukan" as PermitStatus,
        createdAt: new Date("2024-02-01").toISOString(),
        updatedAt: new Date("2024-02-01").toISOString(),
        statusHistory: [
            {
                status: "diajukan" as PermitStatus,
                date: new Date("2024-02-01").toISOString(),
                note: "Permohonan baru diajukan",
            },
        ],
        attachments: [],
    },
    {
        id: "2",
        trackingId: "TRK-2024002",
        type: "hidrologi-kualitas-air",
        applicantName: "Siti Rahmawati",
        applicantEmail: "siti@dlh.gov.id",
        applicantPhone: "081298765432",
        agencyName: "Dinas Lingkungan Hidup",
        agencyCategory: "Instansi Pemerintah",
        subject: "Izin Pengambilan Sampel Kualitas Air Sungai",
        description: "Pengambilan sampel air di 5 titik pantau untuk monitoring limbah industri rutin bulanan.",
        submissionDate: new Date("2024-01-28").toISOString(),
        status: "proses" as PermitStatus,
        createdAt: new Date("2024-01-28").toISOString(),
        updatedAt: new Date("2024-02-02").toISOString(),
        statusHistory: [
            {
                status: "diajukan" as PermitStatus,
                date: new Date("2024-01-28").toISOString(),
                note: "Permohonan diterima",
            },
            {
                status: "proses" as PermitStatus,
                date: new Date("2024-02-02").toISOString(),
                note: "Sedang dalam verifikasi teknis laboratorium",
            },
        ],
        attachments: [],
    },
    {
        id: "3",
        trackingId: "TRK-2024003",
        type: "banjir-bencana",
        applicantName: "Joko Widodo",
        applicantEmail: "joko@bpbd.go.id",
        applicantPhone: "081355556666",
        agencyName: "BPBD Kota Malang",
        agencyCategory: "Instansi Pemerintah",
        subject: "Permohonan Data Kajian Risiko Banjir",
        description: "Data historis banjir 5 tahun terakhir untuk penyusunan dokumen rencana mitigasi bencana daerah.",
        submissionDate: new Date("2024-01-20").toISOString(),
        status: "disetujui" as PermitStatus,
        createdAt: new Date("2024-01-20").toISOString(),
        updatedAt: new Date("2024-01-30").toISOString(),
        statusHistory: [
            {
                status: "diajukan" as PermitStatus,
                date: new Date("2024-01-20").toISOString(),
            },
            {
                status: "proses" as PermitStatus,
                date: new Date("2024-01-25").toISOString(),
            },
            {
                status: "disetujui" as PermitStatus,
                date: new Date("2024-01-30").toISOString(),
                note: "Data telah disiapkan dan dikirim",
            },
        ],
        attachments: [],
    },
    {
        id: "4",
        trackingId: "TRK-2024004",
        type: "informasi-publik",
        applicantName: "Ahmad Fauzi",
        applicantEmail: "ahmad@konsultan.co.id",
        applicantPhone: "081211112222",
        subject: "Permintaan Peta Sebaran Air Tanah",
        description: "Untuk keperluan perencanaan pembangunan perumahan subsidi di wilayah pinggiran.",
        submissionDate: new Date("2024-01-15").toISOString(),
        status: "ditolak" as PermitStatus,
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-01-20").toISOString(),
        statusHistory: [
            {
                status: "diajukan" as PermitStatus,
                date: new Date("2024-01-15").toISOString(),
            },
            {
                status: "ditolak" as PermitStatus,
                date: new Date("2024-01-20").toISOString(),
                note: "Data yang diminta bersifat rahasia negara (Dikecualikan)",
            },
        ],
        rejectionReason: "Informasi yang diminta termasuk dalam kategori informasi yang dikecualikan sesuai UU KIP.",
        attachments: [],
    },
    {
        id: "5",
        trackingId: "TRK-2024005",
        type: "hidrologi-kualitas-air",
        applicantName: "Dewi Sartika",
        applicantEmail: "dewi@konstruksi.com",
        applicantPhone: "081599998888",
        agencyName: "PT. Konstruksi Jaya",
        agencyCategory: "Kontraktor",
        subject: "Rekomendasi Teknis Peil Banjir",
        description: "Permohonan rekomendasi teknis peil banjir untuk pembangunan jembatan baru di jalan provinsi.",
        submissionDate: new Date("2024-02-10").toISOString(),
        status: "diajukan" as PermitStatus,
        createdAt: new Date("2024-02-10").toISOString(),
        updatedAt: new Date("2024-02-10").toISOString(),
        statusHistory: [
            {
                status: "diajukan" as PermitStatus,
                date: new Date("2024-02-10").toISOString(),
                note: "Menunggu penjadwalan survei lapangan",
            },
        ],
        attachments: [],
    },
];
